apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-apps
  namespace: argocd
spec:
  goTemplates: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: grafana
            chart: backend-chart
            chartURL: https://artifacthub.io/packages/helm/grafana/grafana
            valuesFile: apps/grafana/values.yaml
            namespace: prod
  template:
    metadata:
      name: '{{.name | lower }}-prod'
    spec:
      project: default
      sources:
        - repoURL: '{{.chartURL}}'
          targetRevision: main
          chart: '{{chart}}'
          helm:
            valueFiles:
              - $values/{{.valuesFile}}
        - repoURL: 'https://github.com/DocentSzachista/argo-cd-playground'
          targetRevision: test
          ref: values
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
